Populate country level OCD IDs for all countries in the world
opencivicdata/ocd-division-ids pull request #234
Opened 2021-01-28 19:24 UTC by jrunningen

For any country that did not yet have a CSV under identifiers, this
commit adds a CSV that defines the country code for that country.

This was created using the list of officially assigned code elements
from Wikipedia at
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements,
at the time of this commit.

Any countries that already existed in this repository were not touched.

2021-02-02 18:52 UTC, jloutsenhizer requested changes
There's ISO codes for a lot of entities which aren't independent countries. This wiki page has a useful table: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

I think we should probably filter this down to limit to those that are actually countries.

Also it looks like this PR directly creates this `identifiers/country-*.csv` files, but I think we would want the subdirs for each of these to be created as well so that they can each be compiled with the script.

2021-02-02 18:52 UTC, jloutsenhizer commented on identifiers/country-aq.csv
> +ocd-division/country:aq,Antarctica
I don't think this OCD ID would be correct since Antarctica isn't a country.

2021-02-02 18:52 UTC, jloutsenhizer commented on identifiers/country-as.csv
> +ocd-division/country:as,American Samoa
American Samoa is also not a country, but a territory of the US

2021-02-02 18:52 UTC, jloutsenhizer commented on identifiers/country-gu.csv
> +ocd-division/country:gu,Guam
Same as American Samoa

2021-02-02 18:52 UTC, jloutsenhizer commented on identifiers/country-bm.csv
> +ocd-division/country:bm,Bermuda
This is a territory of the UK, so I don't think it should be a separate country.

2021-02-03 03:43 UTC, jrunningen commented
All comments resolved. See the commit messages for details.

2021-02-03 03:52 UTC, jrunningen commented
For the failing test, see #237.

2021-02-03 17:32 UTC, jrunningen commented
I've rebased atop the latest merge to fix the test.

2021-02-19 16:42 UTC, jloutsenhizer approved these changes
I think this looks good to me based on spot checking the added OCD IDs.

2021-02-23 20:16 UTC, jpmckinney commented
To clarify, how were the non-countries filtered out? Are the countries based on the table here, where Sovereignty is either "disputed" or "UN member state"? https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

2021-02-23 21:31 UTC, jrunningen commented
Yes, it's based on [that table](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#Current_ISO_3166_country_codes). The full commit message in eb5e2789eef8d51fa02cc0ad0d4bf981f423762a describes the criteria for filtering a non-country:

```
This is any country code with sovereignty not listed as "UN member
state," "UN observer state," or "disputed," and which did not previously
exist in the respository.
```

2021-02-23 21:50 UTC, jpmckinney approved these changes

2021-02-26 14:31 UTC, merged