adding US Territory OCDIDs
opencivicdata/ocd-division-ids pull request #250
Opened 2021-03-25 17:38 UTC by tomreitz

This is a pull request to add US Territory IDs, per discussion [here](https://partnerissuetracker.corp.google.com/issues/165248225).

2021-04-12 19:11 UTC, jloutsenhizer requested changes

2021-04-12 19:11 UTC, jloutsenhizer commented on identifiers/country-us/us_territory_sldl.csv
> +ocd-division/country:us/territory:as/sldl:1,American Samoa House of Representatives District 1
It looks like Puerto Rico House districts are missing.

2021-04-12 19:11 UTC, jloutsenhizer commented on identifiers/country-us/us_territory_sldu.csv
> +ocd-division/country:us/territory:as/sldu:1,American Samoa Senate District 1
Puerto Rico senate districts are missing

2021-04-12 19:12 UTC, jloutsenhizer commented
You should be able to resolve the failing test by running: `./scripts/compile.py us`

2021-07-12 14:21 UTC, tomreitz commented
@jloutsenhizer I added the Puerto Rico legislative districts as you requested, but running `./scripts/compile.py us` now gives the following error:
```
ERROR: mismatch for attribute name on ocd-division/country:us/territory:pr/sldl:1
was set to Puerto Rico House of Representatives District 1 - got Puerto Rico State House district 1 from identifiers/country-us/census_autogenerated/us_sldl.csv
other sources:
   identifiers/country-us/us_territory_sldl.csv
   identifiers/country-us/census_autogenerated_14/us_sldl.csv
   identifiers/country-us/census_autogenerated_12/us_sldl.csv
   identifiers/country-us/openstates/state-pr-openstates.csv
```
I take this to mean that the Puerto Rico districts are already present in other CSV files? but I'm not sure if you also want them in the `us_territory_sldl.csv` and `us_territory_sldu.csv` files. Please advise. Thanks!

2021-08-12 15:22 UTC, jloutsenhizer commented
I think these changes overall are good, sorry for the delay in re-reviewing.

As for teh error you're getting from the compile script. I believe it's because they already exists and the names are inconsistent between some of the files. I think if you update the names to be consistent, then the compile script should work

2021-09-20 13:17 UTC, tomreitz commented on identifiers/country-us/us_territory_government.csv
> +ocd-division/country:us/territory:mp/region:boe_1,Northern Mariana Islands Board of Education District 1
Thanks, added the headers.

2021-09-20 13:18 UTC, tomreitz commented
@jloutsenhizer I've updated some of the districts names, now the compile script completes successfully. Let me know if you need anything else to accept the pull request. Thanks!

2021-09-20 16:42 UTC, jloutsenhizer approved these changes
Looks good to me. @jpmckinney could you take a second look?

2021-09-20 20:28 UTC, skywalkerdude approved these changes

2021-09-21 13:27 UTC, jpmckinney commented on identifiers/country-us/us_territory_government.csv
> +ocd-division/country:us/territory:mp/region:boe_1,Northern Mariana Islands Board of Education District 1
Why are these region:boe_1 instead of board_of_education:1 ? (`vi` uses the `board_of_education` type.)

2021-09-21 13:27 UTC, jpmckinney commented on identifiers/country-us/us_territory_sldl.csv
> +ocd-division/country:us/territory:as/sldl:1,American Samoa House of Representatives District 1
The style in us_sldl.csv is to lower-case "district".

2021-09-21 13:27 UTC, jpmckinney commented on identifiers/country-us/us_territory_sldu.csv
> +ocd-division/country:us/territory:as/sldu:1,American Samoa Senate District 1
The style in us_sldu.csv is to lower-case "district".

2021-09-21 13:27 UTC, jpmckinney commented on identifiers/country-us/us_territory_sldu.csv
> +ocd-division/country:us/territory:pr/sldu:1,Puerto Rico Senate district I
Any reason for roman numerals?

2022-09-04 11:43 UTC, closed without merging