Bangladesh OCDID Update
opencivicdata/ocd-division-ids pull request #355
Opened 2023-10-12 14:02 UTC by NaviThotlu

Hi @Zohour,

1. Added Bangladesh new constituencies in country-bd.csv
2. Added Bangladesh new constituencies in Jatiya_Sangsad_electorates.csv
3. Added README file.

2023-10-17 12:55 UTC, asmitajha91 commented
@azuser Hi Zohour, could you please help review this PR.

2023-10-23 09:51 UTC, HKSenior requested changes

2023-10-23 09:51 UTC, HKSenior commented on identifiers/country-bd/Jatiya_Sangsad_electorates.csv
According to this [wiki](https://en.wikipedia.org/wiki/List_of_constituencies_of_the_Jatiya_Sangsad) Jatiya Sangsad has 8 divisions. The following districts aren't represented within the additions, please add them:
- Barishal of the Barisal district, 
- Jhalokati of the Barisal district
- Moulivibazar of the Sylhet district

2023-10-23 09:51 UTC, HKSenior commented on identifiers/country-bd/README
> +
nit: remove new line from between list elements.

2023-10-23 09:51 UTC, HKSenior commented on identifiers/country-bd/README
> +* Jatiya_Sangsad_electorates.csv:contains the list of electoral districts for the House of the Nation (Jatiya Sangsad) of Bangladesh
nit: add a space after the colon.

```suggestion
* Jatiya_Sangsad_electorates.csv: contains the list of electoral districts for the House of the Nation (Jatiya Sangsad) of Bangladesh
```

2023-10-25 10:15 UTC, NaviThotlu commented
Hi @HKSenior,

1. We have updated Barisal to Barishal, but for Jhalokati and Moulivibazar we have checked those have names as Jhalokathi and Maulvibazar in the Bangladesh parliament website. Please refer to screen shot below.
![image001](https://github.com/opencivicdata/ocd-division-ids/assets/134617739/66d0fda3-2b09-4a28-a681-a199eee20bff)

2.  we have updated README file with the changes mentioned.

2023-10-25 12:15 UTC, HKSenior requested changes
Thanks for the clarification on the previous divisions.

2023-10-25 12:15 UTC, HKSenior commented on identifiers/country-bd/Jatiya_Sangsad_electorates.csv
> +ocd-division/country:bd/ed:coxs_bazar_1,Cox s Bazar-1
It's okay to have an apostrophe within the name column. Please add here and the following lines.

```suggestion
ocd-division/country:bd/ed:coxs_bazar_1,Cox's Bazar-1
```

Screenshot from website:
![Screenshot 2023-10-25 at 8 10 20 AM](https://github.com/opencivicdata/ocd-division-ids/assets/10860174/fa6d48c2-2425-4610-bd16-e27e5db6cfaf)

2023-10-26 11:16 UTC, NaviThotlu commented
Hi @HKSenior ,

we have added apostrophe in Cox's Bazar.

2023-10-26 14:38 UTC, jloutsenhizer approved these changes
Did a quick spot check, everything looks good to me.

2023-10-26 15:05 UTC, jpmckinney approved these changes
Looks good. Makes sense to omit the division and district from the OCD-ID, and just keep the constituency. (I quickly compared to https://en.wikipedia.org/wiki/List_of_constituencies_of_the_Jatiya_Sangsad)

2023-10-26 15:15 UTC, merged